import com.gradle.publish.PluginConfiguration
import com.gradle.publish.PublishTask

plugins {
    alias libs.plugins.gradle.publish apply false
    alias libs.plugins.project.convention
}

allprojects {
    group = 'xyz.tynn.buildsrc'
}

subprojects {
    pluginManager.withPlugin(libs.plugins.gradle.publish.get().pluginId) {
        java.toolchain.languageVersion = JavaLanguageVersion.of(21)

        gradlePlugin {
            website = 'https://github.com/tynn-xyz/BuildSrc'
            vcsUrl = 'https://github.com/tynn-xyz/BuildSrc'
        }

        tasks.withType(PublishTask).configureEach {
            final hiddenPlugins = objects.domainObjectSet(PluginConfiguration)
            hiddenPlugins.addAllLater providers.provider {
                config.get().plugins.findAll {
                    it.with { !displayName || !description || !tags }
                }
            }
            doFirst { config.get().plugins.removeAll hiddenPlugins }
            doLast { config.get().plugins.addAll hiddenPlugins }
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}
