[versions]
junit = "6.0.2"

[plugins]
gradle-publish = "com.gradle.plugin-publish:2.1.0"
project-convention = "xyz.tynn.convention.project:0.0.5"

[libraries]
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
plugin-android = "com.android.tools.build:gradle:9.1.0"
plugin-kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.0"

[bundles]
junit = ['junit-api', 'junit-params']
plugins-convention = ['plugin-android', 'plugin-kotlin']
