plugins {
    alias libs.plugins.gradle.publish
    id 'groovy-gradle-plugin'
}

gradlePlugin {
    final mainId = 'xyz.tynn.convention.project'
    plugins {
        register('main') {
            id = mainId
            implementationClass = 'XyzTynnConventionProjectPlugin'
            displayName = 'Project convention plugin'
            description = 'Configures all Android modules, the Maven release and the Versions plugin'
            tags.set(['android', 'convention', 'release', 'versions', 'wrapper'])
        }
    }
    afterEvaluate {
        plugins {
            remove(named(mainId))
        }
    }
}

test {
    environment 'SIGNING_KEY', 'key'
    environment 'SIGNING_PASSWORD', 'pwd'
}

dependencies {
    testRuntimeOnly libs.junit.platform
    testImplementation libs.bundles.junit

    testRuntimeOnly libs.bundles.plugins.convention
}
