subprojects {
    final mainPluginId = "xyz.tynn.convention.${project.name}"
    final mainPluginName = "convention${project.name.capitalize()}Plugin"

    plugins.withId(libs.plugins.gradle.publish.get().pluginId) {
        gradlePlugin.plugins {
            register(mainPluginName) {
                id = mainPluginId
                implementationClass = 'unknown'
            }
        }
    }

    plugins.withId('groovy-gradle-plugin') {
        afterEvaluate {
            gradlePlugin.plugins {
                final mainPluginDup = named(mainPluginId)
                named(mainPluginName) {
                    implementationClass = mainPluginDup.get().implementationClass
                }
                remove mainPluginDup
            }
        }
    }

    plugins.withId('maven-publish') {
        publishing.publications.configureEach {
            artifactId = "convention-${project.name}"
        }
    }
}

evaluationDependsOnChildren()
['build', 'check', 'publishPlugins', 'publishToMavenLocal'].each { name ->
    tasks.register(name) {
        dependsOn subprojects*.tasks*.named(name)
    }
}
